tools/biosnoop: Fix biosnoop pattern option (#5304)
The code to support the block_io tracepoints failed to update some
code that is used with the -P option. That code changed the second
argument of __trace_req_completion from 'req' to 'key', but in the
"#ifdef INCLUDE_PATTERN" block, the use of 'req' remained unchanged.
Of course, 'key' should be use here too.

Also remove the commented out line of code related to rq_disk.

It fixes the following error:
$ biosnoop -P
/virtual/main.c:213:24: error: use of undeclared identifier 'req'
  213 |         data.pattern = req->__sector == *sector ? SEQUENTIAL : RANDOM;
      |                        ^
/virtual/main.c:216:19: error: use of undeclared identifier 'req'
  216 |     last_sector = req->__sector + data.len / 512;
      |                   ^
2 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biosnoop", line 335, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.13/site-packages/bcc/__init__.py", line 505, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>
Signed-off-by: Monu Lakshkar <mlakshkar@newrelic.com>